### PR TITLE
Create new Gradle projects with gauge-java 0.7.9

### PR DESCRIPTION
**Pull request by jreznot**
This updates default version of gauge-java for new Gradle projects to 0.7.9

### CODE REVIEW

**Comment by jreznot** [comment]
I don't mind if someone changes it instead of me, seems I need to use DCO (

**Comment by sriv** [comment]
DCO check requires that you sign your commits (i.e. use `git commit --sign-off`). If this is an issue for you, I'm happy to close this PR and make the change.

Thanks for point out the stale template.

**Comment by jreznot** [comment]
Thanks, I've added sign-off.

**Comment by jreznot** [comment]
@sriv Do you know how to propagate it to the `gauge init`? Do we need any additional actions? 
I've implemented Maven/Gradle project creation for IntelliJ plugin and it seems gauge-java 0.7.9 required for correct work with latest gauge version.

**Comment by sriv** [comment]
@jreznot - all done, the actions are automated and you should be able to use the [latest release template](https://github.com/getgauge/template-java-gradle/releases/tag/v0.0.5) now.

**Pull request merged**
